### ISSUE TITLE
Error and Shutdown Server

### ISSUE THREAD

**Issue by excaliburkim** [TwiDev/SpectralDamage#13]
**Describe the bug**

[15:44:57] [Server thread/ERROR]: Error occurred while disabling SpectralDamage v2.5.1
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at ch.twidev.spectraldamage.SpectralDamagePlugin.lambda$3(SpectralDamagePlugin.java:126) ~[spectraldamage-2.5.1.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at ch.twidev.spectraldamage.SpectralDamagePlugin.onDisable(SpectralDamagePlugin.java:125) ~[spectraldamage-2.5.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:147) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.disablePlugins(CraftServer.java:584) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:986) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:862) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1288) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2152]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TwiDev** [comment]
Hello !

Thank for your issue,

Does this error only occur when you voluntarily shut down the server and not before? Or is there an error before from spectral damage that crashes the server?

**Comment by excaliburkim** [comment]
> Hello !
> 
> Thank for your issue,
> 
> Does this error only occur when you voluntarily shut down the server and not before? Or is there an error before from spectral damage that crashes the server?

It wasn't there before, but suddenly it appeared for the first time.

**Comment by TwiDev** [comment]
Hello !
sorry for the late response.

I plan to do a pretty big update in 1 to 2 weeks which should fix this bug. because I have very little time available,
Thank you very much for your issue I will investigate the problem!

**Comment by TwiDev** [comment]
The functionality is done and should appear in the next version of the plugin which will be released shortly
